version: '3.3'

services:

  dovecot:
    image: flavioaiello/dovecot
    environment:
      - POSTMASTER=postmaster
      - DOMAIN=vcap.me
      - HOSTNAMES=mail.vcap.me
      - RECIPIENT_DELIMITER=+
    ports:
      - "143:143"
      - "993:993"
      - "995:995"
      - "4190:4190"
    volumes:
      - /tmp/mailstack/data:/data
      - /tmp/mailstack/mail:/mail
      - /tmp/mailstack/certs:/certs
      - /tmp/mailstack/overrides:/overrides
    healthcheck:
      test: nc -w 7 -zvv 0.0.0.0 143
      interval: 30s
      timeout: 30s
      retries: 20
    deploy:
      resources:
        reservations:
          cpus: '0.05'
          memory: 1024M
        limits:
          memory: 1024M
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10

  postfix:
    image: flavioaiello/postfix
    environment:
      - DOMAIN=vcap.me
      - HOSTNAME=mail.vcap.me
      - MESSAGE_SIZE_LIMIT=50000000
      - RELAYNETS=172.16.0.0/12
      - RELAYHOST=
      - RECIPIENT_DELIMITER=+
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
    volumes:
      - /tmp/mailstack/data:/data
      - /tmp/mailstack/certs:/certs
      - /tmp/mailstack/overrides:/overrides
    healthcheck:
      test: nc -w 7 -zvv 0.0.0.0 587
      interval: 30s
      timeout: 30s
      retries: 20
    deploy:
      resources:
        reservations:
          cpus: '0.05'
          memory: 1024M
        limits:
          memory: 1024M
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10

  clamav:
    image: flavioaiello/clamav
    volumes:
      - /tmp/mailstack/filter:/data
    healthcheck:
      test: nc -w 7 -zvv 0.0.0.0 3310
      interval: 30s
      timeout: 30s
      retries: 20
    deploy:
      resources:
        reservations:
          cpus: '0.05'
          memory: 1024M
        limits:
          memory: 1024M
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10

  freshclam:
    image: flavioaiello/freshclam
    volumes:
      - /tmp/mailstack/filter:/data
    deploy:
      resources:
        reservations:
          cpus: '0.05'
          memory: 1024M
        limits:
          memory: 1024M
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10

  rspamd:
    image: flavioaiello/rspamd
    volumes:
      - /tmp/mailstack/filter:/var/lib/rspamd
    healthcheck:
      test: nc -w 7 -zvv 0.0.0.0 587
      interval: 30s
      timeout: 30s
      retries: 20
    deploy:
      resources:
        reservations:
          cpus: '0.05'
          memory: 1024M
        limits:
          memory: 1024M
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10

  radicale:
    image: flavioaiello/radicale
    build: ./radicale
    volumes:
      - /tmp/mailstack/dav:/data
    healthcheck:
      test: nc -w 7 -zvv 0.0.0.0 587
      interval: 30s
      timeout: 30s
      retries: 20
    deploy:
      resources:
        reservations:
          cpus: '0.05'
          memory: 1024M
        limits:
          memory: 1024M
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10

networks:
  default:
    driver: overlay
