version: '3.3'

services:

  dovecot:
    # image: flavioaiello/mailstack-dovecot
    build: ./dovecot
    environment:
      - POSTMASTER=postmaster
      - DOMAIN=vcap.me
      - HOSTNAMES=mail.vcap.me
      - RECIPIENT_DELIMITER=+
    ports:
      - "143:143"
      - "993:993"
      - "995:995"
      - "4190:4190"
    volumes:
      - /tmp/mailstack/data:/data
      - /tmp/mailstack/mail:/mail
      - /tmp/mailstack/certs:/certs
      - /tmp/mailstack/overrides:/overrides
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  postfix:
    #image: flavioaiello/mailstack-mailstack
    build: ./postfix
    environment:
      - DOMAIN=vcap.me
      - HOSTNAME=mail.vcap.me
      - MESSAGE_SIZE_LIMIT=50000000
      - RELAYNETS=172.16.0.0/12
      - RELAYHOST=
      - RECIPIENT_DELIMITER=+
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
    volumes:
      - /tmp/mailstack/data:/data
      - /tmp/mailstack/certs:/certs
      - /tmp/mailstack/overrides:/overrides
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  clamav:
    # image: flavioaiello/mailstack-clamav
    build: ./clamav
    volumes:
      - /tmp/mailstack/filter:/data
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  freshclam:
    # image: flavioaiello/mailstack-freshclam
    build: ./freshclam
    volumes:
      - /tmp/mailstack/filter:/data
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  rspamd:
    # image: flavioaiello/mailstack-rspamd
    build: ./rspamd
    volumes:
      - /tmp/mailstack/filter:/var/lib/rspamd
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  radicale:
    # image: flavioaiello/mailstack-radicale
    build: ./radicale
    volumes:
      - /tmp/mailstack/dav:/data
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
